language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake libXxf86vm-dev libxml2
install:
    - export GLFW="true"
    - export PORTAUDIO="true"
    - export SDL2="true"
    - export SDL2_TTF="true"
    - export SDL_MIXER="true"
    - bash install.sh
    - ls ./lib
script:
    - file lib/libglfw3.a
    - file lib/libportaudio.so
    - file lib/libSDL2-2.0.so.0
    - file lib/libSDL2_mixer.so
    - file lib/libSDL2_ttf.so
